### ISSUE TITLE
Unable to connect to Azure IoT Central

### ISSUE THREAD

**Issue by limengdu** [SeeedJP/wioterminal-aziot-example#9]
I tried to connect to Azure IoT Central based on the Wiki below, and although the Azure page was different from the one described in the Wiki, I was able to find all the relevant information needed in the Wiki.
https://wiki.seeedstudio.com/Connect-Wio-Terminal-to-Microsoft-Azure-IoT-Central/
I have set up the SSID and password for the wio terminal via PuTTY and have also set up az_iotc in the format shown below.
![chrome_QE6D88MyCs](https://user-images.githubusercontent.com/37475446/187341124-0119e1e5-f79f-42ef-bdf0-ae70fe7ef221.png)
After resetting, the Wio Terminal was able to connect to WiFi without any problems, but it never connected to Azure and it would get stuck on this page.
![1b3e6b22537d3942ce014ce5d5ce2751](https://user-images.githubusercontent.com/37475446/187341378-f86a77cb-b00c-48ed-a543-f7cf43aae511.jpg)
The project is urgent and I would be grateful if you could help to resolve this issue as soon as possible.

**Comment by matsujirushi** [comment]
Hi @limengdu ,
I think the screen for getting the values ​​to be set in the Wio Terminal is wrong.

**Azure IoT Central Application:** Security > Permissions > Device connection groups > SAS-IoT-Devices

![image](https://user-images.githubusercontent.com/8079404/187358510-cfc2dfdf-6cd1-49d9-9027-4da740d2b69a.png)

Please check and try it.
